/*
 * Generated by Bluespec Compiler, version 2016.07.beta1 (build 34806, 2016-07-05)
 * 
 * On Thu Feb  1 22:35:02 IST 2018
 * 
 */
#include "bluesim_primitives.h"
#include "model_mkTestArithmeticBarrelShifter.h"

#include <cstdlib>
#include <time.h>
#include "bluesim_kernel_api.h"
#include "bs_vcd.h"
#include "bs_reset.h"


/* Constructor */
MODEL_mkTestArithmeticBarrelShifter::MODEL_mkTestArithmeticBarrelShifter()
{
  mkTestArithmeticBarrelShifter_instance = NULL;
}

/* Function for creating a new model */
void * new_MODEL_mkTestArithmeticBarrelShifter()
{
  MODEL_mkTestArithmeticBarrelShifter *model = new MODEL_mkTestArithmeticBarrelShifter();
  return (void *)(model);
}

/* Schedule functions */

static void schedule_posedge_CLK(tSimStateHdl simHdl, void *instance_ptr)
       {
	 MOD_mkTestArithmeticBarrelShifter &INST_top = *((MOD_mkTestArithmeticBarrelShifter *)(instance_ptr));
	 INST_top.DEF_CAN_FIRE_RL_testShifter = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_testShifter = INST_top.DEF_CAN_FIRE_RL_testShifter;
	 if (INST_top.DEF_WILL_FIRE_RL_testShifter)
	   INST_top.RL_testShifter();
	 if (do_reset_ticks(simHdl))
	 {
	   INST_top.INST_counter.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_lfsr_r.rst_tick__clk__1((tUInt8)1u);
	 }
       };

/* Model creation/destruction functions */

void MODEL_mkTestArithmeticBarrelShifter::create_model(tSimStateHdl simHdl, bool master)
{
  sim_hdl = simHdl;
  init_reset_request_counters(sim_hdl);
  mkTestArithmeticBarrelShifter_instance = new MOD_mkTestArithmeticBarrelShifter(sim_hdl,
										 "top",
										 NULL);
  bk_get_or_define_clock(sim_hdl, "CLK");
  if (master)
  {
    bk_alter_clock(sim_hdl, bk_get_clock_by_name(sim_hdl, "CLK"), CLK_LOW, false, 0llu, 5llu, 5llu);
    bk_use_default_reset(sim_hdl);
  }
  bk_set_clock_event_fn(sim_hdl,
			bk_get_clock_by_name(sim_hdl, "CLK"),
			schedule_posedge_CLK,
			NULL,
			(tEdgeDirection)(POSEDGE));
  (mkTestArithmeticBarrelShifter_instance->set_clk_0)("CLK");
}
void MODEL_mkTestArithmeticBarrelShifter::destroy_model()
{
  delete mkTestArithmeticBarrelShifter_instance;
  mkTestArithmeticBarrelShifter_instance = NULL;
}
void MODEL_mkTestArithmeticBarrelShifter::reset_model(bool asserted)
{
  (mkTestArithmeticBarrelShifter_instance->reset_RST_N)(asserted ? (tUInt8)0u : (tUInt8)1u);
}
void * MODEL_mkTestArithmeticBarrelShifter::get_instance()
{
  return mkTestArithmeticBarrelShifter_instance;
}

/* Fill in version numbers */
void MODEL_mkTestArithmeticBarrelShifter::get_version(unsigned int *year,
						      unsigned int *month,
						      char const **annotation,
						      char const **build)
{
  *year = 2016u;
  *month = 7u;
  *annotation = "beta1";
  *build = "34806";
}

/* Get the model creation time */
time_t MODEL_mkTestArithmeticBarrelShifter::get_creation_time()
{
  
  /* Thu Feb  1 17:05:02 UTC 2018 */
  return 1517504702llu;
}

/* Control run-time licensing */
tUInt64 MODEL_mkTestArithmeticBarrelShifter::skip_license_check()
{
  return 0llu;
}

/* State dumping function */
void MODEL_mkTestArithmeticBarrelShifter::dump_state()
{
  (mkTestArithmeticBarrelShifter_instance->dump_state)(0u);
}

/* VCD dumping functions */
MOD_mkTestArithmeticBarrelShifter & mkTestArithmeticBarrelShifter_backing(tSimStateHdl simHdl)
{
  static MOD_mkTestArithmeticBarrelShifter *instance = NULL;
  if (instance == NULL)
  {
    vcd_set_backing_instance(simHdl, true);
    instance = new MOD_mkTestArithmeticBarrelShifter(simHdl, "top", NULL);
    vcd_set_backing_instance(simHdl, false);
  }
  return *instance;
}
void MODEL_mkTestArithmeticBarrelShifter::dump_VCD_defs()
{
  (mkTestArithmeticBarrelShifter_instance->dump_VCD_defs)(vcd_depth(sim_hdl));
}
void MODEL_mkTestArithmeticBarrelShifter::dump_VCD(tVCDDumpType dt)
{
  (mkTestArithmeticBarrelShifter_instance->dump_VCD)(dt,
						     vcd_depth(sim_hdl),
						     mkTestArithmeticBarrelShifter_backing(sim_hdl));
}
