/*
 * Generated by Bluespec Compiler, version 2016.07.beta1 (build 34806, 2016-07-05)
 * 
 * On Thu Feb  1 23:00:32 IST 2018
 * 
 */
#include "bluesim_primitives.h"
#include "model_mkTestLogicalLeftBarrelShifter.h"

#include <cstdlib>
#include <time.h>
#include "bluesim_kernel_api.h"
#include "bs_vcd.h"
#include "bs_reset.h"


/* Constructor */
MODEL_mkTestLogicalLeftBarrelShifter::MODEL_mkTestLogicalLeftBarrelShifter()
{
  mkTestLogicalLeftBarrelShifter_instance = NULL;
}

/* Function for creating a new model */
void * new_MODEL_mkTestLogicalLeftBarrelShifter()
{
  MODEL_mkTestLogicalLeftBarrelShifter *model = new MODEL_mkTestLogicalLeftBarrelShifter();
  return (void *)(model);
}

/* Schedule functions */

static void schedule_posedge_CLK(tSimStateHdl simHdl, void *instance_ptr)
       {
	 MOD_mkTestLogicalLeftBarrelShifter &INST_top = *((MOD_mkTestLogicalLeftBarrelShifter *)(instance_ptr));
	 INST_top.DEF_CAN_FIRE_RL_testShifter = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_testShifter = INST_top.DEF_CAN_FIRE_RL_testShifter;
	 if (INST_top.DEF_WILL_FIRE_RL_testShifter)
	   INST_top.RL_testShifter();
	 if (do_reset_ticks(simHdl))
	 {
	   INST_top.INST_counter.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_lfsr_r.rst_tick__clk__1((tUInt8)1u);
	 }
       };

/* Model creation/destruction functions */

void MODEL_mkTestLogicalLeftBarrelShifter::create_model(tSimStateHdl simHdl, bool master)
{
  sim_hdl = simHdl;
  init_reset_request_counters(sim_hdl);
  mkTestLogicalLeftBarrelShifter_instance = new MOD_mkTestLogicalLeftBarrelShifter(sim_hdl,
										   "top",
										   NULL);
  bk_get_or_define_clock(sim_hdl, "CLK");
  if (master)
  {
    bk_alter_clock(sim_hdl, bk_get_clock_by_name(sim_hdl, "CLK"), CLK_LOW, false, 0llu, 5llu, 5llu);
    bk_use_default_reset(sim_hdl);
  }
  bk_set_clock_event_fn(sim_hdl,
			bk_get_clock_by_name(sim_hdl, "CLK"),
			schedule_posedge_CLK,
			NULL,
			(tEdgeDirection)(POSEDGE));
  (mkTestLogicalLeftBarrelShifter_instance->set_clk_0)("CLK");
}
void MODEL_mkTestLogicalLeftBarrelShifter::destroy_model()
{
  delete mkTestLogicalLeftBarrelShifter_instance;
  mkTestLogicalLeftBarrelShifter_instance = NULL;
}
void MODEL_mkTestLogicalLeftBarrelShifter::reset_model(bool asserted)
{
  (mkTestLogicalLeftBarrelShifter_instance->reset_RST_N)(asserted ? (tUInt8)0u : (tUInt8)1u);
}
void * MODEL_mkTestLogicalLeftBarrelShifter::get_instance()
{
  return mkTestLogicalLeftBarrelShifter_instance;
}

/* Fill in version numbers */
void MODEL_mkTestLogicalLeftBarrelShifter::get_version(unsigned int *year,
						       unsigned int *month,
						       char const **annotation,
						       char const **build)
{
  *year = 2016u;
  *month = 7u;
  *annotation = "beta1";
  *build = "34806";
}

/* Get the model creation time */
time_t MODEL_mkTestLogicalLeftBarrelShifter::get_creation_time()
{
  
  /* Thu Feb  1 17:30:32 UTC 2018 */
  return 1517506232llu;
}

/* Control run-time licensing */
tUInt64 MODEL_mkTestLogicalLeftBarrelShifter::skip_license_check()
{
  return 0llu;
}

/* State dumping function */
void MODEL_mkTestLogicalLeftBarrelShifter::dump_state()
{
  (mkTestLogicalLeftBarrelShifter_instance->dump_state)(0u);
}

/* VCD dumping functions */
MOD_mkTestLogicalLeftBarrelShifter & mkTestLogicalLeftBarrelShifter_backing(tSimStateHdl simHdl)
{
  static MOD_mkTestLogicalLeftBarrelShifter *instance = NULL;
  if (instance == NULL)
  {
    vcd_set_backing_instance(simHdl, true);
    instance = new MOD_mkTestLogicalLeftBarrelShifter(simHdl, "top", NULL);
    vcd_set_backing_instance(simHdl, false);
  }
  return *instance;
}
void MODEL_mkTestLogicalLeftBarrelShifter::dump_VCD_defs()
{
  (mkTestLogicalLeftBarrelShifter_instance->dump_VCD_defs)(vcd_depth(sim_hdl));
}
void MODEL_mkTestLogicalLeftBarrelShifter::dump_VCD(tVCDDumpType dt)
{
  (mkTestLogicalLeftBarrelShifter_instance->dump_VCD)(dt,
						      vcd_depth(sim_hdl),
						      mkTestLogicalLeftBarrelShifter_backing(sim_hdl));
}
